all: ClientCP1.java ServerCP1.java ClientCP2.java ServerCP2.java
	javac ClientCP1.java ServerCP1.java ClientCP2.java ServerCP2.java

clean:
	rm ClientCP1.class
	rm ServerCP1.class
	rm ClientCP2.class
	rm ServerCP2.java